# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - keywordtensor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Prepare strict deployment package
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev libpng-dev
          mkdir deploy_workspace
          cp -r demo/* deploy_workspace/
          cp -r keywordtensor deploy_workspace/
          pip install --upgrade pip
          pip install -r deploy_workspace/requirements.txt --target="deploy_workspace/.python_packages/lib/site-packages"
          cd deploy_workspace
          zip -r ../release.zip .
                
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A7FB180042304AD6A7606705944C7B8B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ABBCFFA73C1D49ABACE5194221F23242 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_942815E023324E2980421C76571E43E6 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'keywordtensor'
          slot-name: 'Production'
          package: release.zip